---
functional:
  - Возможность зарегистрироваться в личном кабинете с помощью e-mail.
  - Возможность авторизации через Github.
  - Возможность авторизации и голосового чата через Discord.
  - Ведение рейтинга зарегистрированных пользователей (Далее - Участников и/или Игроков) по неделе/месяцу/всего и его отображение на главной странице. 
  - Возможность сортировки по рейтингу, количеству игр и т.д.
  - Возможность организации турниров и турнирной сетки.
  - Возможность просмотра истории баттлов.
  - Возможность просмотра повтора баттла.
  - Возможность просмотра баттла зрителям в режиме online.
  - Возможность пользователю без регистрации подключиться к простой случайной игре с ботом.
  - Возможность незарегистрированному пользователу во время случайной игры (SIMPLE BATTLE) использовать все инструменты игры, доступные Игроку (за исключением, выхода из баттла с последующим возвращением и записи баттла).
  - Возможность Участника при создании лобби кастомизировать - уровень сложности, тип задачи, теги и временной лимит.
  - Возможность Участника выбрать тип игры - с другим пользователем, с другом по ссылке, с ботом.
  - Возможность Участникам просматривать списки игр и подключаться к доступным для подключения играм, созданными другими Игроками
  - Уведомление о начале баттла и отображение преигровой страницы с указанием Игроков (слева - Игрок, справа - соперник), далее - страница игры.
  - Возможность отображения двух редакторов кода для Игроков (слева - редактор Игрока, справа - соперника).
  - Запрет на копирование кода в окне редактора.
  - Мультиязычность задач (русский и английский).
  - Возможность просматривать краткую обучающую справку по игре (Show guide).
  - Поддержка всех популярных языков программирования.
  - Возможность выбора языка программирования в терминале баттла.
  - Возможность изменять язык программирования в ходе баттла.
  - Возможность перехода редактора vim-режим.
  - Возможность просматривать процесс написания кода соперником в режиме online.
  - Возможность Участника во время баттла выйти из игры и переподключиться к баттлу. 
  - Возможность продолжать играть, если соперник "вылетел"/вышел из баттла.
  - Возможность Участника во время баттла проверить своё решение неограниченное количество раз.
  - Возможность остаться в баттле после определения победителя (или окончания установленного лимита на таймере) и дописать код / ознакомиться с кодом.
  - Возможность закончить игру, сдавшись без написания кода.
  - Результаты баттла при отсутствии выявленного победителя по окончанию отсчета времена, заданного на таймере, не сохраняются и не влияют на рейтинг.
  - Возможность участников отправлять сообщения в общий чат и уникальный игровой чат. 
  - В истории должна быть иконка напротив никнейма, указывающая на победителя баттла.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть удобным на мобильном устройстве.
  - Доступность оставления обратной связи в случае нахождения бага или предложения возможности для улучшения.
implicit:
  - Участник не может писать и изменять код соперника.
  - Зрители не могут писать код и вносить изменения в код участников.
  - Зрители не могут писать и отправлять комментарии в уникальный игровой чат участников баттла.
  - Пользователи не могут вносить изменения в таблицу лидеров вручную.
  - Участники не могут вносить изменения в предустановленную задачу баттла.
  - После окончания баттла история игрового чата удаляется.